[WIP] CSCFAIRMETA-684: [ADD] Integrate Etsin SSO
CSCfi/etsin-finder pull request #546
Opened 2020-09-17 11:31 UTC by MattiasLevlin

- Integrate Etsin SSO with Fairdata SSO

2020-09-17 14:08 UTC, MattiasLevlin commented
To do:
- Set all required SSO session variables in authentication.py
- Account for different environments (test/stable/demo...) in variable names/functions

2020-09-18 12:10 UTC, MattiasLevlin commented
Correction to previous commit: - There are ida_projects and idm_groups, but no **ida_groups**

2020-09-18 14:50 UTC, MattiasLevlin commented
Functional now:
- Login/logout
- Retrieving datasets
- Publishing datasets

To do:
- Enable adding files from IDA
- Account for different environments (test/stable/demo...) in variable names/functions

Related [WIP] PR: https://github.com/CSCfi/etsin-ops/pull/31

2020-09-22 11:43 UTC, MattiasLevlin commented
Prerequisites:
https://github.com/CSCfi/etsin-ops/pull/32

For testing instructions, see:
https://wiki.eduuni.fi/display/cscetsin/Etsin%3A+SSO

Description:
- Integrates Etsin and Qvain with Fairdata SSO
- For now, both use Etsin authentication

What should be verified as functional:
- Login/logout
- Publishing and updates to datasets
- Adding files from IDA using v1 & v2 filepickers
- Deleting files and datasets

2020-09-23 11:14 UTC, tahme requested changes
Looks good. Tested locally that login works, and when Etsin and Qvain Light run in separate `.local.fd-test.csc.fi` domains, logging into Etsin logs you also into Qvain as it's supposed to work. I have just a few minor cleanup suggestions.

I did notice that the relay parameter of the Etsin /sso endpoint is not working with SSO. It's the parameter that redirects you back to the page where you were after you login. That can be fixed in a separate issue.

2020-09-23 13:26 UTC, MattiasLevlin commented on etsin_finder/frontend/js/components/dataset/events/index.jsx
> +      url = `https://etsin.fd-test.csc.fi/dataset/${identifier}`
Addressed in 7845232

2020-09-23 13:34 UTC, MattiasLevlin commented on etsin_finder/qvain_light_utils.py
> +        user_ida_projects_ids = [project for project in user_ida_projects]
Addressed in 84a398b

2020-09-23 13:40 UTC, MattiasLevlin commented
> I did notice that the relay parameter of the Etsin /sso endpoint is not working with SSO. It's the parameter that redirects you back to the page where you were after you login. That can be fixed in a separate issue.

Good catch. This can be addressed in the next PR (CSCFAIRMETA-685), which should separate the Qvain login from the Etsin one.

2020-09-24 11:32 UTC, MattiasLevlin commented
Commit 644c7ad requires https://github.com/CSCfi/etsin-ops/pull/33/files and addresses issues with logging in in test and demo, if the direct proxy is used

2020-09-28 08:57 UTC, tahme requested changes

2020-09-28 08:57 UTC, tahme commented on etsin_finder/frontend/js/components/general/loggedInUser.jsx
> +  const { firstName, lastName } = user
I think we should only show the first name. We initially tried to show both names but it took too much space. Or if it's possible that only one of them is defined, maybe show `firstName || lastName`.

2020-09-28 10:37 UTC, tahme approved these changes
:+1:

2020-09-28 10:41 UTC, merged