CSCFAIRMETA-672-Enable-info-button-for-embargo-datasets
CSCfi/etsin-finder pull request #551
Opened 2020-09-21 13:34 UTC by katrite

- Set allowDataIdaInfoButton to true for embargo datasets in all cases

2020-09-22 13:20 UTC, MattiasLevlin requested changes
I think allowDataIdaInfoButton can be enabled for all datasets.

2020-09-25 07:08 UTC, katrite commented
> I think allowDataIdaInfoButton can be enabled for all datasets.

-Removed allowDataIdaInfoButton from everywhere since it was always 'True'

2020-09-25 08:46 UTC, tahme approved these changes

2020-09-25 12:43 UTC, MattiasLevlin approved these changes

2020-09-25 13:35 UTC, merged