CSCFAIRMETA: Split Qvain translations to separate files
CSCfi/etsin-finder pull request #818
Opened 2021-05-06 12:43 UTC by tahme

2021-05-07 07:38 UTC, ismotee requested changes

2021-05-07 07:38 UTC, ismotee commented on etsin_finder/frontend/locale/english/qvain.js
> +const qvainFinnish = {
qvainEnglish?

2021-05-07 07:38 UTC, ismotee commented on etsin_finder/frontend/locale/english/qvain.js
> +export default qvainFinnish
qvainEnglish

2021-05-07 07:44 UTC, tahme commented on etsin_finder/frontend/locale/english/qvain.js
> +const qvainFinnish = {
fixed

2021-05-07 07:44 UTC, tahme commented on etsin_finder/frontend/locale/english/qvain.js
> +export default qvainFinnish
fixed

2021-05-10 12:07 UTC, ismotee approved these changes

2021-05-11 06:20 UTC, merged